version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=phytosynergy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=E6fgO4KM7xDkXbysGVLhFEflgZuEZu14xKoBxh5G7FA
    restart: always

  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:E6fgO4KM7xDkXbysGVLhFEflgZuEZu14xKoBxh5G7FA@db:5432/phytosynergy_db
      - DJANGO_SECRET_KEY=aky@!o6_4fyp%ox59q^xfe0*#^6n83(dz)rjs!c34j-+ul3%u^
      - DEBUG=0 # Set to 0 for production
      - ALLOWED_HOSTS=192.168.1.35,localhost
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Maps port 80 on the server to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume: