# Generated by Django 5.2.4 on 2025-07-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AntibioticClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        help_text="e.g., Beta-lactam, Aminoglycoside",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phytochemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compound_name", models.CharField(max_length=255, unique=True)),
                (
                    "pubchem_cid",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="PubChem CID"
                    ),
                ),
                (
                    "canonical_smiles",
                    models.TextField(
                        blank=True, null=True, verbose_name="Canonical SMILES"
                    ),
                ),
                (
                    "inchi_key",
                    models.CharField(
                        blank=True,
                        max_length=27,
                        null=True,
                        unique=True,
                        verbose_name="InChI Key",
                    ),
                ),
                (
                    "molecular_weight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "pmid",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="PMID"
                    ),
                ),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("article_title", models.TextField(blank=True, null=True)),
                ("journal", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Antibiotic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("antibiotic_name", models.CharField(max_length=255, unique=True)),
                (
                    "drugbank_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="DrugBank ID",
                    ),
                ),
                (
                    "antibiotic_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="synergy_data.antibioticclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pathogen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genus", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("strain", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gram_stain",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Gram-positive, Gram-negative",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("genus", "species", "strain")},
            },
        ),
        migrations.CreateModel(
            name="SynergyExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mic_phyto_alone",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="MIC of Phyto Alone",
                    ),
                ),
                (
                    "mic_abx_alone",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="MIC of Antibiotic Alone",
                    ),
                ),
                (
                    "mic_phyto_in_combo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="MIC of Phyto in Combination",
                    ),
                ),
                (
                    "mic_abx_in_combo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="MIC of Antibiotic in Combination",
                    ),
                ),
                (
                    "mic_units",
                    models.CharField(
                        default="µg/mL", max_length=20, verbose_name="MIC Units"
                    ),
                ),
                (
                    "fic_index",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="FIC Index",
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Synergy", "Synergy (FIC ≤ 0.5)"),
                            ("Additive", "Additive (0.5 < FIC ≤ 1.0)"),
                            ("Indifference", "Indifference (1.0 < FIC ≤ 4.0)"),
                            ("Antagonism", "Antagonism (FIC > 4.0)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "moa_observed",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observed Mechanism of Action",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "antibiotic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="synergy_data.antibiotic",
                    ),
                ),
                (
                    "pathogen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="synergy_data.pathogen",
                    ),
                ),
                (
                    "phytochemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="synergy_data.phytochemical",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="synergy_data.source",
                    ),
                ),
            ],
        ),
    ]
