# Generated by Django 4.2.23 on 2025-07-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synergy_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteViewCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The total number of page views for the site.",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="antibioticclass",
            options={
                "verbose_name": "Antibiotic Class",
                "verbose_name_plural": "Antibiotic Classes",
            },
        ),
    ]
