# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synergy_data", "0002_siteviewcounter_alter_antibioticclass_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="phytochemical",
            name="chemical_class",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Chemical Class",
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="chemical_subclass",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Chemical Subclass",
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="chemical_superclass",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Chemical Superclass",
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="hba",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="H-Bond Acceptors",
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="hbd",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="H-Bond Donors",
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="molecular_formula",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Molecular Formula",
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="rotatable_bonds",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Rotatable Bonds",
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="tpsa",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="TPSA (\u00c5\u00b2)",
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="xlogp",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="XLogP",
            ),
        ),
    ]
