# Generated by Django 4.2.23 on 2026-03-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synergy_data", "0003_phytochemical_chemical_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phytochemical",
            name="heavy_atom_count",
            field=models.IntegerField(
                blank=True, help_text="Number of heavy (non-hydrogen) atoms", null=True
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="is_drug_like",
            field=models.BooleanField(
                default=False, help_text="Passes Lipinski RO5 with ≤1 violation"
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="lipinski_violations",
            field=models.IntegerField(
                blank=True,
                help_text="Number of Lipinski Rule of 5 violations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="logp",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Partition coefficient (Wildman-Crippen LogP)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phytochemical",
            name="num_rings",
            field=models.IntegerField(
                blank=True, help_text="Number of rings", null=True
            ),
        ),
        migrations.AddField(
            model_name="synergyexperiment",
            name="assay_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checkerboard", "Checkerboard"),
                    ("time_kill", "Time-Kill"),
                    ("disk_diffusion", "Disk Diffusion"),
                    ("broth_microdilution", "Broth Microdilution"),
                    ("other", "Other"),
                ],
                default="checkerboard",
                help_text="Experimental method used to determine synergy",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=255, unique=True)),
                (
                    "common_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("family", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phytochemicals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="source_plants",
                        to="synergy_data.phytochemical",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
            },
        ),
    ]
